# Linear regression with TensorFlow

In [9]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_california_housing

loading data:

In [8]:
housing=fetch_california_housing()

preparing explanatory data for linear regression:

In [7]:
m,n=housing.data.shape
housing_plus_bias=np.c_[np.ones([m,1]),housing.data]

creating graph for computation of coefficients of linear regression:

In [10]:
tf.reset_default_graph()
X=tf.constant(housing_plus_bias, name='X', dtype=tf.float64)
y=tf.constant(housing.target.reshape(-1,1), name='y', dtype=tf.float64)
XT=tf.transpose(X)
theta=tf.matmul(tf.matrix_inverse(tf.matmul(XT,X)), tf.matmul(XT,y))
#theta=tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT,X)),XT),y)

list of operations made on the graph:

In [11]:
gf=tf.get_default_graph()
gf.get_operations()

[<tf.Operation 'X' type=Const>,
 <tf.Operation 'y' type=Const>,
 <tf.Operation 'transpose/Rank' type=Rank>,
 <tf.Operation 'transpose/sub/y' type=Const>,
 <tf.Operation 'transpose/sub' type=Sub>,
 <tf.Operation 'transpose/Range/start' type=Const>,
 <tf.Operation 'transpose/Range/delta' type=Const>,
 <tf.Operation 'transpose/Range' type=Range>,
 <tf.Operation 'transpose/sub_1' type=Sub>,
 <tf.Operation 'transpose' type=Transpose>,
 <tf.Operation 'MatMul' type=MatMul>,
 <tf.Operation 'MatrixInverse' type=MatrixInverse>,
 <tf.Operation 'MatMul_1' type=MatMul>,
 <tf.Operation 'MatMul_2' type=MatMul>]

evaluating theta on the graph -computing coefficients of the linear regression:

In [12]:
with tf.Session() as sess:
    theta_val=theta.eval()
theta_val

array([[-3.69419202e+01],
       [ 4.36693293e-01],
       [ 9.43577803e-03],
       [-1.07322041e-01],
       [ 6.45065694e-01],
       [-3.97638942e-06],
       [-3.78654265e-03],
       [-4.21314378e-01],
       [-4.34513755e-01]])

### Comparison to scikit-learn Linear Regression:

In [16]:
from sklearn.linear_model import LinearRegression
lrg=LinearRegression()
lrg.fit(housing.data, housing.target.reshape(-1,1))
lrg.intercept_,lrg.coef_

(array([-36.94192021]),
 array([[ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,
          6.45065694e-01, -3.97638942e-06, -3.78654265e-03,
         -4.21314378e-01, -4.34513755e-01]]))